"""agregar campo disciplina a user

Revision ID: 72782303d9fb
Revises: cefbeb6a2879
Create Date: 2025-09-04 09:06:51.960403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72782303d9fb'
down_revision = 'cefbeb6a2879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disciplina', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('disciplina')

    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='playing_with_neon_pkey')
    )
    # ### end Alembic commands ###
